name = "gnat_native"
version = "11.2.2"
provides = ["gnat=11.2.2"]
description = "The GNAT Ada compiler - Native"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"

auto-gpr-with = false

[configuration]
disabled = true

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[origin."case(os)".linux."case(host-arch)".aarch64]
url = "https://github.com/reznikmm/GNAT-FSF-builds/releases/download/gnat-11.2.0-2/gnat-aarch64-linux-11.2.0-2.tar.gz"
hashes = ["sha256:960cfd9e2abecd19c55358746db86e56b55b91ca8dd9d95eba7492592acd1d2c"]
binary = true
